### ISSUE TITLE
Joining a chat, it always steps in at the very bottom, even if there are new messages notified

### ISSUE THREAD

**Issue by mattbel10** [ChristianPauly/fluffychat#47]
**Actual Behavior**
When I get notified for the presence of a bunch of new messages not read yet, I always step at the very bottom of the chat. This is annoying since, in case of a long new messages list (for instance 100 new messages), I'm obliged to slide up until to get to last read messages, trying to remember where I left the chat before.
**Desired behaviour**
When joining a chat, I wish to be redirected automatically to the last read message, without worrying about what I missed before.

**Comment by ChristianPauly** [comment]
Thanks, I have some ideas how to implement this feature. In fact it is implemented but the problem is, that the server will send only the last 10 messages, if there are more then 10 new messages and the app has to remove the local messages archive to avoid gaps in the history. So the feature is not really working. But I will implement a system which will automatically fill the gaps.

**Comment by mattbel10** [comment]
Thank you Christian for the explanation. Needless to say, you made a great job with FluffyChat, which is already amazing.

**Comment by ChristianPauly** [comment]
There might be a new specification about this: https://matrix.org/docs/spec/client_server/r0.4.0.html#fully-read-markers

**Comment by ChristianPauly** [comment]
Implemented in latest commit
