### ISSUE TITLE
Support formatted messages

### ISSUE THREAD

**Issue by timsueberkrueb** [ChristianPauly/fluffychat#98]
* [ ] Allow sending formatted messages (markdown)
* [ ] Display formatted messages

**Comment by ChristianPauly** [comment]
Hey, so far I have decided to not implement this feature. There is a list of features which I won't implement at the moment: https://www.patreon.com/posts/what-fluffychat-23575662

The reason is: FluffyChat should be a dead simple messenger app which even my grandma can use and not a powerful collaboration tool like Riot. The only exception are hyperlinks and linebreaks.
